### ISSUE TITLE
0.63 is broken, can't switch between windows

### ISSUE THREAD

**Issue by NoXPhasma** [robint99/dock-applet#22] opened 2015-07-23 13:35 UTC
The last commit broke the dock on mate 1.10. I can't switch between open windows. Open new windows and minimize them works though. But they can't unminimized.

Tested with marco and compiz.

***
Linux Mint 17.2 x64
Mate 1.10

**Comment by robint99** [comment] 2015-07-23 13:45
When the mouse is over the app's icon, you can now use the mouse wheel to
cycle through all of the app's open windows. Give that a try and let me how
how you get on...

**Comment by NoXPhasma** [comment] 2015-07-23 15:56
That works and it is a nice feature.

But I would suggest to give it still the ability to click on the icon to bring all opened windows to the front.

**Comment by NoXPhasma** [comment] 2015-07-23 16:17
About the Firefox launcher, it seems that version 0.63 is confused by the actual binary of Firefox located in `/usr/lib/firefox` and the `/usr/bin/firefox`

When I create a new launcher with the executable `/usr/lib/firefox/firefox` it works.

**Comment by NoXPhasma** [comment] 2015-07-23 16:23
Ok, now everything works like intended, mouse click brings up last active window. It was probably needed to change some pinned apps or display order because of the new config save path.

I will keep that issue open, because you might need to look into it.

**Comment by milankni** [comment] 2015-07-31 15:30
I occassionally also have problems (with the new version) that some windows do not get WM focus after clicking on the dock icon (typically firefox, skype; while for other apps it works always w/o problems).

A workaround is that I have to hover the mouse over the icon, wait for the list of windows and then click on any of them (even if there is only one window). After that, a simple clicking on the dock icon works again as it always did. Well, until next time the bug occurs.

P.S. The scrolling through windows by a mouse wheel is really nice.

**Comment by robint99** [comment] 2015-08-04 19:43
I'll have a look at this as soon as I get the chance, but it may be a
little while. I'm currently moving home and am going to be without the
internet for two or three weeks :(

**Comment by robint99** [comment] 2015-09-08 09:44
I've just committed a fix for unminimizing windows. The dock will now always bring back the app's last active window or (if it doesn't know what the last active window was) the app's first opened window. 

In the next couple of days I'm going to add a configuration option so that users can choose whether to restore just the last active window or all windows, and while I'm doing that I'll also take a look at the Firefox issue....

**Comment by NoXPhasma** [comment] 2015-09-08 10:05
It works for me, thank you.

**Comment by milankni** [comment] 2015-09-08 11:34
It seems to work for me, too.

BTW, while you're at it: how about adding a right-click-menu item "open new window" (the same like SHIFT + mouse click), maybe just below the "Close all windows" at the top of the menu. Occassionally, I am lazilly using the mouse only and this feature would help...

**Comment by robint99** [comment] 2015-09-17 09:53
I've now committed the changes for the new configuration option so it's now possible to choose whether to restore all windows or just the last active one when an app's dock icon is clicked.

Next on my todo list - the firefox issue and also adding the 'open new window' right click menu option.

**Comment by milankni** [comment] 2015-09-19 11:37
You're doing a nice job.

BTW, I have added another small request ;-) https://github.com/robint99/dock-applet/issues/24

**Comment by robint99** [comment] 2015-09-21 10:27
The open new window right click option is now done. I've also looked into the firefox problem and it seems that installing the latest version of firefox on linux mint also creates a .desktop file in ~/.local/share/applications. However this .desktop file does not specify which icon to use and this is why the applet defaulted to the cog icon. I've fixed this by using the app name for the icon name if no icon is specified.

Both fixes have been committed and are up on github.

**Comment by NoXPhasma** [comment] 2015-09-21 11:15
The "open new window" menu option works fine, except for Firefox. It does not open a new window. Not sure if this is a bug or intended.

The Firefox launcher is now fixed.

**Comment by milankni** [comment] 2015-09-21 16:18
"open new window" works fine for chromium, mate-terminal, caja.

It does not work for LibreOffice and Pluma (also with SHIFT + left click) - maybe it has never worked, I never tried it.

**Comment by NoXPhasma** [comment] 2015-09-21 16:20
The "open new window" on Firefox works, it was a problem on my side.

**Comment by robint99** [comment] 2015-09-23 09:02
I've been thinking about how 'open new window' works, and since the current way of doing things (quick and dirty and easy to implement) doesn't work for all apps e.g. pluma and dconf-editor and probably a lot of others, I'm going to re-write it and do it properly this time. ;)

What this means is that the applet will read an app's .desktop file and if it finds any right click options specified there, it will provide them on the right click menu. For example, if you right clicked on Chrome you'd get  'New window' and "New incognito window" options, whereas with LibreOffice Writer you'd get a 'New Document" option. So, the applet will be able to provide right click new window functionality to those apps which support it, but unfortunately not for any others. However, I may leave the 'shift-click' functionality in the applet as an 'unsupported and undocumented feature'..... 

I'll get started on this in the next couple of days...

**Comment by milankni** [comment] 2015-09-23 15:39
This sounds interesting.  

I quickly checked chromium.desktop - there is no action defined, Chrome seems different then...
Among all the apps I have installed, only LibreOffice, Firefox, and GmusicBrowser have some extra actions.

So it seems the user would have to update quite a few .desktop files manually and protect them from being overwritten by package manager on update. And report upstream and hope for inclusion.

Or do you plan to merge .desktop files on the fly if two files exist? (E.g. in /home/user/.local/share/applications and /usr/share/applications)

**Comment by robint99** [comment] 2015-09-24 08:29
The applet looks for .desktop files in ~/.local/share/applications before
it looks in /usr/share/applications. Therefore if a user wanted to add
their own right click actions to an app, they could copy the .desktop from
/usr/share/applications to ~/.local/share/applications and then edit the
new file. This would be quite an advanced thing to do thought, so I'm not
sure how many users would actually want to do this. But if would be useful
to e.g. get pluma to provide a 'new window' action.

**Comment by NoXPhasma** [comment] 2015-09-24 14:00
I just want to add that for me now the Firefox launcher is totally weird, when I start Firefox and pin the launcher to the dock, I can open Firefox from it and the dock will use the launcher also as indicator for the opened program <- as expected.

But when I restart the mate-panel, or restart the desktop/computer the dock applet opens up a new icon for the Firefox, every time.

This only happens to Firefox, when I delete the launcher in `~/.local/share/applications`, the dock can't open firefox anymore. It also doesn't help to copy the launcher from `/usr/share/applications` to `~/.local/share/applications`.

I have no idea why this happens and deleting the config file doesn't help at all.

**Comment by robint99** [comment] 2015-09-27 15:32
I've committed the code for reading right click options from the .desktop file. Up to 4 are supported but I can easily raise that limit if any apps are found that have more than this number. The 'open new window' has been removed as well.

The firefox issue issue is next on my list....

**Comment by robint99** [comment] 2015-09-28 09:27
Hi NoXPhasma,

I've been trying to duplicate your firefox problems, but everything works just fine for me. This is on Linux Mint 17.2 and Firefox 41 downloaded from mozilla.org

To help me duplicate your exact setup, could you let me know  how you installed firefox into /usr/lib - for example, was it by using a PPA or by downloading a .deb, or by going to mozilla.org? Did you uninstall the original firefox first? Could you also attach your firefox .desktop files from  /usr/share/applications and ~/.local/share/applications.

Thanks.

**Comment by NoXPhasma** [comment] 2015-09-28 09:58
I've had Firefox installed from the repositories, which has created a multi language .desktop file in `/usr/share/applications`. I've then uninstalled Firefox and used the package from mozilla and installed it in my home directory.

The problems were gone. I've now installed it from the repositories again and it opens up again a new icon, this is the content of the `/usr/share/applications/firefox.desktop`: https://gist.github.com/NoXPhasma/6853d26b9344de85ad74

**Comment by robint99** [comment] 2015-09-29 15:05
I've spent a while looking at this now, and I think part of the problem is the .desktop files a manually installed firefox places in ~/.local/share/applications. One thing that will happen is that the first time this vesion of firefox is run, there will be no .desktop file for it and therefore the applet will display a cog icon. Pinning and clicking this icon to the dock won't do any good because the applet doesn't have the .desktop file and therefore it doesn't know how to start firefox. The solution is to close firefox and start it again, because by this time it will have created a .desktop file in ~./local/share/applications and the applet will find this and create a new icon in the dock for you. This icon can be pinned etc. and will work as normal.

Other problems can occur can if you delete the manually installed firefox because the .desktop files in ~/.local/share/applications get left behind, and the dock will always find and use these in preference to any in /usr/share/applications. Since these .files relate to deleted copies of Firefox, you can imagine that the applet is going to get confused. 

So the bottom line is that if you're now just using firefox from the repositories, I'm hoping that if you delete all of the firefox .desktop files in ~/.local/share/applications (their names start with 'userapp-Firefox'), remove all of your pinned firefox icons from the dock, close firefox and restart it, all should be ok.

Let me know how you get on with this.

Cheers

**Comment by NoXPhasma** [comment] 2015-09-30 01:10
Yes, it worked to delete all firefox .desktop files.

But this is really weird, that I have to delete all firefox .desktop
files, even those which are regularly installed by the package manager.
I hope you can get this fixed, I don't think users should fiddle around
with this stuff :)

Am 29.09.2015 um 17:05 schrieb robint99:

**Closed** 2015-10-05 13:38 UTC
