### ISSUE TITLE
dock applet doesnt appear on panel

### ISSUE THREAD

**Issue by sandikata** [robint99/dock-applet#7] opened 2015-06-01 08:36 UTC
i tryied to add dock applet on panel but it doesnt appear, how can check what is missing ?
I am on gentoo with mate 1.8

**Comment by robint99** [comment] 2015-06-01 13:51
The first thing to do is check that you have the dependencies installed. The applet needs Python 3 and gir1.2-wnck-1.0 in order to run and without them it just won't start.

If that doesn't help, let me know and I'll install Gentoo in a virtual machine and find out exactly what's going wrong.

Cheers,

Robin

**Comment by sandikata** [comment] 2015-06-02 14:26
So i still cant get it work.. I guess needed package is libwnck but if you have time try in virtual machine with gentoo. If you going to install on vm i wrote ebuild for dock-applet. In my layman overlay ROKO__

**Comment by sandikata** [comment] 2015-06-03 07:09
calculate ~ # ls /usr/lib64/girepository-1.0/
Atk-1.0.typelib         freetype2-2.0.typelib  GdkX11-3.0.typelib        GModule-2.0.typelib       libxml2-2.0.typelib     PangoFT2-1.0.typelib     Wnck-1.0.typelib    xrandr-1.3.typelib
cairo-1.0.typelib       Gdk-2.0.typelib        Gio-2.0.typelib           GnomeKeyring-1.0.typelib  MateMenu-2.0.typelib    PangoXft-1.0.typelib     Wnck-3.0.typelib
DBus-1.0.typelib        Gdk-3.0.typelib        GIRepository-2.0.typelib  GObject-2.0.typelib       Notify-0.7.typelib      Polkit-1.0.typelib       xfixes-4.0.typelib
DBusGLib-1.0.typelib    GdkPixbuf-2.0.typelib  GL-1.0.typelib            Gtk-2.0.typelib           Pango-1.0.typelib       PolkitAgent-1.0.typelib  xft-2.0.typelib
fontconfig-2.0.typelib  GdkX11-2.0.typelib     GLib-2.0.typelib          Gtk-3.0.typelib           PangoCairo-1.0.typelib  win32-1.0.typelib        xlib-2.0.typelib

i have needed library Wnck-1.0.typelib but still not appear on panel..
Python 3.4.1 is installed is it fine ?!

**Comment by sandikata** [comment] 2015-06-03 07:57
I need info man... all is installed and mate is updated to 1.8.1 but doesnt work... What can be wrong ?!

**Comment by sandikata** [comment] 2015-06-03 10:46
i got it work, but there is another question...
from mate applet selector just doesnt start.. i have to start it by hand all the time...

python 3.4 /usr/lib/mate-applets/mate-dock-applet/dock_applet.py

http://s1.hostingkartinok.com/uploads/images/2015/06/8c01d08671cffcdc25e13ec86fee4bd8.png
http://s1.hostingkartinok.com/uploads/images/2015/06/d6bbc323e27ca0156601aba209896f09.png
http://s7.hostingkartinok.com/uploads/images/2015/06/9eb6f172bf6f4bd3242745583fe1fa71.png

any ideas ?!

**Comment by robint99** [comment] 2015-06-03 11:42
You've got further with this than I have. Right now I'm still working on getting MATE installed in Gentoo - compiling everything from source takes ages....

From your screenshots I think I may know what the problem is though. If you open the /usr/share/dbus-1/services/org.mate.panel.applet.DockAppletFactory.service file in nano, you should see a line that starts with 'Exec='. This should point to the location of dock_applet.py e.g. 'Exec='/usr/lib/mate-applets/mate-dock-applet/dock_applet.py'. If it doesn't, then the applet won't start from the applet selector.

If the Exec= line was wrong, could you let me know what it was pointing to so that I figure out what went wrong during the install?

Thanks.

**Comment by sandikata** [comment] 2015-06-03 12:01
i make it work with dirty patch
https://github.com/sandikata/ROKO__/tree/master/x11-misc/dock-applet

because in gentoo python3 is not by default and there is python-targets and if whole system is in python2 by default (like is it) there is needed to make dirty hacks.. Because i dont know how to implement this.. 

http://s7.hostingkartinok.com/uploads/images/2015/06/dd7b9b163309f5db97d04cbe4d136efb.png

offtopic.. do you have idea why systray not following theme style ?

**Comment by robint99** [comment] 2015-06-03 12:18
Glad you got it sorted. The installation process should have handled the Python2/3 thing, so when I've got MATE and Gentoo working I'll see about fixing that.

Sorry, I've got no idea why the systray isn't theming properly. I've sometimes seen one or two icons go wrong if you use a panel size of more than 24 pixels, but I've never seen anything like your problem. Maybe its an issue with the theme itself???

**Comment by sandikata** [comment] 2015-06-03 13:35
this happens with all themes, i increase panel size to 30 pixels

**Comment by robint99** [comment] 2015-06-05 12:24
I've installed and reinstalled the applet on my Gentoo VM a few times now and its working ok there. I can only think your problems might be because during your attempts to install the applet you've ended up with files in some odd locations.

I think I'll have a go at creating an ebuild for the applet, just to make the installation easier on Gentoo.

**Comment by sandikata** [comment] 2015-06-05 12:30
i have ebuild i wrote one but is not the best. It working but the only think that i hack is dirty patch... If you can figure out. But at least working. I can help you for ebuild.

**Comment by robint99** [comment] 2015-06-05 13:14
Could you send me the ebuild you wrote that would be a big help as I've
never written one before :)

**Comment by sandikata** [comment] 2015-06-05 13:58
https://github.com/sandikata/ROKO__/tree/master/x11-misc/dock-applet

**Comment by milankni** [comment] 2015-06-19 19:16
Hi robint99,
on Arch Linux, the applet did not start due to two reasons:
1) missing dependency for python-xdg package in the AUR PKGBUILD file.
2) make sure that all the py files in /usr/lib/mate-applets/mate-dock-applet are executable (now they have 0644 permissions only).

I assume the latter would be an issue also for sandikata @ gentoo, which he workaround by adding /usr/bin/python3 before the applet on the exec line.

**Comment by robint99** [comment] 2015-07-02 11:18
Hi Sandikata,

I've been looking at making an ebuild for the past couple of days and I've made slight improvements to yours. Here it is below:

# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

EAPI=5
inherit autotools eutils git-r3 
DESCRIPTION="Application dock for the MATE panel"
HOMEPAGE="https://github.com/robint99/dock-applet"
EGIT_REPO_URI="https://github.com/robint99/dock-applet.git"

LICENSE="GPL-3"
SLOT="0"
KEYWORDS="~x86 ~amd64"
IUSE=""

DEPEND="dev-lang/python:3.4
	x11-libs/libwnck:1[introspection]
	mate-base/mate-panel[introspection]
	dev-python/pygobject:3[python_targets_python3_4]
	dev-python/pyxdg[python_targets_python3_4]
	dev-python/pygtksourceview
	sys-devel/automake:1.15"
RDEPEND="${DEPEND}"

src_prepare() {
    eaclocal
    eautomake --add-missing
    eautoreconf
}

src_configure() {
    econf --prefix=/usr
}

There are still a couple of problems with it. The gsettings schema the applet needs is compiled but not installed by the ebuild, and all of the .py files are installed without the executable bit set, even though I explicitly set them in the makefile. I've spent a lot of time looking for a solution to these two problems, but I'm not making any progress and have decided that I'm just going to have to leave it to someone else with more experience of writing ebuilds to figure out. 

However, starting with the next version of the applet I'll be distributing a tarball that can be installed using the standard ./configure, make, make install method. I've just tried this now in a gentoo virtual machine and it worked fine although obviously I had to install the applet dependencies myself beforehand.

**Comment by robint99** [comment] 2015-07-02 11:28
Hi milankni,

I've updated the package on the AUR so that it includes the python-xdg dependency. As for the .py files not being marked as executable, I've never seen this on anything but Gentoo and as I mentioned in the message above, the executable bit is explicitly set by the makefile. I'll keep watching out for this in future but in the meantime I'll mark this as closed.

**Closed by robint99** 2015-07-02 11:28 UTC

**Comment by sandikata** [comment] 2015-11-06 10:02
robint99 so if you have progress you can give me link for tarball to test it. and i can make ebuild with all dependencies that is needed.

**Comment by robint99** [comment] 2015-11-12 09:55
Sorry, I've been forgetting to make links for the tarballs. Thanks for
reminding me :)

You can get the latest version (0.64) from

http://github.com/robint99/dock-applet/raw/master/dock-applet-0.64.tar.gz

Just unpack it and do the usual automake, autoreconf etc. instructions to
compile it.

On Fri, Nov 6, 2015 at 10:02 AM, Росен Александров <notifications@github.com
